### PR TITLE
perf(dock): avoid re-creating observer whenever menu is opened

### PR DESCRIPTION
**Pull request by jgroth**
The intersection observer was re-created every time the button in the menu was clicked, causing the callback to be invoked multiple times

## Review:
- [ ] Commits are [atomic](https://seesparkbox.com/foundry/atomic_commits_with_git)
- [ ] Commits have the correct *type* for the changes made
- [ ] Commits with *breaking changes* are marked as such

### Browsers tested:
(Check any that applies, it's ok to leave boxes unchecked if testing something didn't seem relevant.)

Windows:
- [ ] Chrome
- [ ] Edge
- [ ] Firefox

Linux:
- [ ] Chrome
- [ ] Firefox

macOS:
- [ ] Chrome
- [ ] Firefox
- [ ] Safari

Mobile:
- [ ] Chrome on Android
- [ ] iOS

### CODE REVIEW

**Comment by hannahu** [comment]
Looks good! How can I test it?

**Comment by jgroth** [comment]
> Looks good! How can I test it?

You can add a logpoint in the callback and see that it's only called once when a many is opened :upside_down_face: 
It will be invoked one more time for each time it's clicked without this fix

**Comment by hannahu** [comment]
> > Looks good! How can I test it?
> 
> You can add a logpoint in the callback and see that it's only called once when a many is opened 🙃 It will be invoked one more time for each time it's clicked without this fix

Yeah I was thinking if there was another way to test if it caused more trouble.

**Review by hannahu — APPROVED** [review]

**Comment by hannahu** [comment]
Some docs are failing?

**Pull request merged**
