### PR TITLE
package(feat): upgrade Kompendium from v.0.7.3 to v.0.8.6

### PR DESCRIPTION
**Pull request by Kiarokh**
## Review:
- [ ] Commits are [atomic](https://seesparkbox.com/foundry/atomic_commits_with_git)
- [ ] Commits have the correct *type* for the changes made
- [ ] Commits with *breaking changes* are marked as such

### Browsers tested:
(Check any that applies, it's ok to leave boxes unchecked if testing something didn't seem relevant.)

Windows:
- [ ] Chrome
- [ ] Edge
- [ ] Firefox

Linux:
- [ ] Chrome
- [ ] Firefox

macOS:
- [ ] Chrome
- [ ] Firefox
- [ ] Safari

Mobile:
- [ ] Chrome on Android
- [ ] iOS

### CODE REVIEW

**Comment by jgroth** [comment]
I'm not sure why we needed a new PR for this and didn't just use the old one :smile: :thinking: :upside_down_face:

**Comment by Kiarokh** [comment]
@jgroth could we? I don't know how 😄 🙈

**Comment by adrianschmidt** [comment]
> @jgroth could we? I don't know how 😄 🙈

You just push new commits to the branch the first PR was created from… You do that every day… 😄

**Comment by Kiarokh** [comment]
🤯 WTF 😆

**Pull request closed without merging**
