### PR TITLE
fix(text-editor): fix bug where html was interpreted as markdown

### PR DESCRIPTION
**Pull request by adrianschmidt**
This fixes a bug introduced by #3318

## Review:
- [ ] Commits are [atomic](https://seesparkbox.com/foundry/atomic_commits_with_git)
- [ ] Commits have the correct *type* for the changes made
- [ ] Commits with *breaking changes* are marked as such

### Browsers tested:
(Check any that applies, it's ok to leave boxes unchecked if testing something didn't seem relevant.)

Windows:
- [ ] Chrome
- [ ] Edge
- [ ] Firefox

Linux:
- [ ] Chrome
- [ ] Firefox

macOS:
- [ ] Chrome
- [ ] Firefox
- [ ] Safari

Mobile:
- [ ] Chrome on Android
- [ ] iOS

### CODE REVIEW

**Review by FredrikWallstrom — APPROVED** [review]
From an email story point of view: Approved!

Thank you for promptly addressing this.

**Comment by adrianschmidt** [comment]
> From an email story point of view: Approved!
> 
> Thank you for promptly addressing this ❤️

Awesome!

I'm gonna say it's approved from a lime-elements point of view too! 😁

**Comment by john-traas** [comment]
❤️ 🚀 🔥 🔥 🔥

**Pull request merged**
