### PR TITLE
chore(text editor): bump prosemirror-model to 1.22.1

### PR DESCRIPTION
**Pull request by john-traas**
As per this [post here](https://discuss.prosemirror.net/t/heads-up-xss-risk-in-domserializer/6572) we should update to prosemirror-model 1.22.1 as it contains a fix for a vulnerability to xss attacks in the DOMSerialiser.

### CODE REVIEW

**Review by adrianschmidt — DISMISSED** [review]
Seems reasonable.

I just did a very quick smoke test, making sure it was possible to write stuff in the basic example, and that we got the updated value output.

**Review by adrianschmidt — CHANGES_REQUESTED** [review]
This should be a `fix`, so it creates a new release, and it's good if the commit message says what the benefit to the consumer is. Something like:

```
fix(text-editor): update prosemirror-model to 1.22.1 to fix XSS vulnerability
```

**Comment by john-traas** [comment]
> This should be a `fix`, so it creates a new release, and it's good if the commit message says what the benefit to the consumer is. Something like:
> 
> ```
> fix(text-editor): update prosemirror-model to 1.22.1 to fix XSS vulnerability
> ```

⚡ Updated

**Review by adrianschmidt — APPROVED** [review]

**Pull request merged**
