### PR TITLE
Unify input field layouts

### PR DESCRIPTION
**Pull request by Kiarokh**
fix: https://github.com/Lundalogik/lime-elements/issues/754
fix: https://github.com/Lundalogik/lime-elements/issues/728

## Review:
- [x] Commits are [atomic](https://seesparkbox.com/foundry/atomic_commits_with_git)
- [x] Commits have the correct *type* for the changes made
- [x] Commits with *breaking changes* are marked as such

### Browsers tested:
(Check any that applies, it's ok to leave boxes unchecked if testing something didn't seem relevant.)

Windows:
- [ ] Chrome
- [ ] Edge
- [ ] Firefox

Linux:
- [ ] Chrome
- [ ] Firefox

macOS:
- [x] Chrome
- [x] Firefox
- [ ] Safari

Mobile:
- [ ] Chrome on Android
- [ ] iOS

### CODE REVIEW

**Comment by Kiarokh** [comment]
@adrianschmidt I used `fix` for two different issues here. Hope this is correctly done, and as you meant. ;)

**Comment by adrianschmidt** [comment]
> @adrianschmidt I used `fix` for two different issues here. Hope this is correctly done, and as you meant. ;)

Looks like GitHub linked the issues correctly 👍

**Comment by terryilebode6** [comment]
the commit marked as a chore should have a scope, so something like chore(lime-elements): .......

**Comment by Kiarokh** [comment]
To test this properly, we need to have Limel- Select, -Picker, and -Input 

1- beside each other, and 
2- under each other. 

And see how they are laid out, and whether they align correctly or not. A good place to do that is in the object cards (Fullscreen view Vs. Related view). But I don't know which object has all these 3 fields together. (optimally, we also need a Slider in there too, because my next task will be unifying the layout of the slider with these 3 guys)

Another solution is to make an example in limel-form and put all of these together in the form and test it there.

**Comment by adrianschmidt** [comment]
> the commit marked as a chore should have a scope, so something like chore(lime-elements): .......

A scope isn't required, and adding the scope `lime-elements` is completely redundant, since that doesn't narrow anything down at all. So I think that chore is fine without a scope.

**Comment by terryilebode6** [comment]
while placed horizontally , the items still look not aligned properly  
image

**Pull request merged**
