### PR TITLE
Fix list darkmode

### PR DESCRIPTION
**Pull request by Kiarokh**
## Review:
- [ ] Commits are [atomic](https://seesparkbox.com/foundry/atomic_commits_with_git)
- [ ] Commits have the correct *type* for the changes made
- [ ] Commits with *breaking changes* are marked as such

### Browsers tested:
(Check any that applies, it's ok to leave boxes unchecked if testing something didn't seem relevant.)

Windows:
- [ ] Chrome
- [ ] Edge
- [ ] Firefox

Linux:
- [ ] Chrome
- [ ] Firefox

macOS:
- [ ] Chrome
- [ ] Firefox
- [ ] Safari

Mobile:
- [ ] Chrome on Android
- [ ] iOS

### CODE REVIEW

**Comment by LucyChyzhova** [comment]
Found it a bit inconsistent : 
In the light mode: 
`List with action menu` has a darker hover effect. 
`List with custom styles` has a white hover effect.
 
in the Dark mode, we have the opposite behavior.
 
should we follow the same behavior, or what do you think?  🤔 

https://user-images.githubusercontent.com/50618208/212695558-e3f2060f-68d1-4b2b-8beb-c876aeef11c3.mov

**Comment by LucyChyzhova** [comment]
Other than that looks good!

**Review by LucyChyzhova — APPROVED** [review]

**Review by LucyChyzhova — CHANGES_REQUESTED** [review]
Noticed changes in the normal (light) view for the `Find page`  OR  should I skip it for now? 
Screenshot 2023-01-16 at 17 30 54

**Comment by Kiarokh** [comment]
great find @LucyChyzhova I'll fix and pusha fixup

**Comment by Kiarokh** [comment]
⚡

**Review by LucyChyzhova — APPROVED** [review]

**Pull request merged**
