### PR TITLE
fix(menu-list): import styles from `limel-list` to remove duplicate css

### PR DESCRIPTION
**Pull request by Kiarokh**
fix: https://github.com/Lundalogik/crm-feature/issues/2460

## Review:
- [ ] Commits are [atomic](https://seesparkbox.com/foundry/atomic_commits_with_git)
- [ ] Commits have the correct *type* for the changes made
- [ ] Commits with *breaking changes* are marked as such

### Browsers tested:
(Check any that applies, it's ok to leave boxes unchecked if testing something didn't seem relevant.)

Windows:
- [ ] Chrome
- [ ] Edge
- [ ] Firefox

Linux:
- [ ] Chrome
- [ ] Firefox

macOS:
- [ ] Chrome
- [ ] Firefox
- [ ] Safari

Mobile:
- [ ] Chrome on Android
- [ ] iOS

### CODE REVIEW

**Comment by LucyChyzhova** [comment]
I have checked out your branch and a got some bugs, take a look at screenshots 👇, please 
[(component/limel-list/)](http://localhost:3333/#/component/limel-list/)
Some layout changes:
image

When you hover an item:
image
image

Some layout changes and a hovering problem:
image

**Comment by Kiarokh** [comment]
Thanks @LucyChyzhova Good catch. I think it's because the branch is out-dated. We fixed these issues somewhere else. I'll update it now and we can check again in a while :)

**Comment by Kiarokh** [comment]
OK, I updated the branch and don't see those issues ;)

**Comment by LucyChyzhova** [comment]
yes, now everything is correct! 🎉

**Review by LucyChyzhova — APPROVED** [review]

**Comment by adrianschmidt** [comment]
@LucyChyzhova Good catch, even though it turned out to be a false alarm 🙂

Please make sure to always rebase on the latest version of the target branch (`next` in this case) before reviewing. (Imagine if this problem had not been there before rebasing, but appeared _after_ rebasing. Then reviewing without rebasing first would have missed the problem.)

**Pull request merged**
