### PR TITLE
feat(select): enable narrow layouts 

### PR DESCRIPTION
**Pull request by Kiarokh**
fix: https://github.com/Lundalogik/crm-feature/issues/1797

## Review:
- [ ] Commits are [atomic](https://seesparkbox.com/foundry/atomic_commits_with_git)
- [ ] Commits have the correct *type* for the changes made
- [ ] Commits with *breaking changes* are marked as such

### Browsers tested:
(Check any that applies, it's ok to leave boxes unchecked if testing something didn't seem relevant.)

Windows:
- [ ] Chrome
- [ ] Edge
- [ ] Firefox

Linux:
- [ ] Chrome
- [ ] Firefox

macOS:
- [ ] Chrome
- [ ] Firefox
- [ ] Safari

Mobile:
- [ ] Chrome on Android
- [ ] iOS

### CODE REVIEW

**Review by jensgustafsson — APPROVED** [review]
👏👏👏

**Comment by Kiarokh** [comment]
lint is complaining here, but I don't understand what it wants me to do. I had linted it before pushing

**Comment by adrianschmidt** [comment]
> lint is complaining here, but I don't understand what it wants me to do. I had linted it before pushing

It's the formatting. Just run `npm run lint:fix` and prettier will fix it for you.

**Comment by Kiarokh** [comment]
tnx. linted it again. works now :)

**Review by jensgustafsson — APPROVED** [review]

**Pull request merged**
