### PR TITLE
 fix(select): better visualize invalid state

### PR DESCRIPTION
**Pull request by Kiarokh**
fix: https://github.com/Lundalogik/crm-feature/issues/2166

## Review:
- [x] Commits are [atomic](https://seesparkbox.com/foundry/atomic_commits_with_git)
- [x] Commits have the correct *type* for the changes made
- [x] Commits with *breaking changes* are marked as such

### Browsers tested:
(Check any that applies, it's ok to leave boxes unchecked if testing something didn't seem relevant.)

Windows:
- [ ] Chrome
- [ ] Edge
- [ ] Firefox

Linux:
- [ ] Chrome
- [ ] Firefox

macOS:
- [x] Chrome
- [ ] Firefox
- [ ] Safari

Mobile:
- [ ] Chrome on Android
- [ ] iOS

### CODE REVIEW

**Review by sampsonbryce — DISMISSED** [review]

**Comment by sampsonbryce** [comment]
LGTM @adrianschmidt can you double check the review pls?

**Review by adrianschmidt — CHANGES_REQUESTED** [review]
Just "requesting changes" to prevent merge until I've reviewed 🙂

**Comment by Kiarokh** [comment]
I was thinking… I wanna use `limel-icon` instead of embedding it in the CSS.

**Comment by Befkadu1** [comment]
> I was thinking… I wanna use `limel-icon` instead of embedding it in the CSS.

yes it is possible to insert the icon above this line https://github.com/Lundalogik/lime-elements/blob/7f7b998d4e53274f6c816d37e956e48e660de678/src/components/select/select.template.tsx#L93

**Comment by adrianschmidt** [comment]
> I was thinking… I wanna use `limel-icon` instead of embedding it in the CSS.

I think that icons that are defined by the components themselves, rather than by the consumer, are better to embed. That way, they are included for anyone else using lime-elements, even if they don't have access to lime-icons8…

(Even better if you would like to design icons @Kiarokh, then we don't have to worry about what exactly is permitted by icons8's license agreement…)

**Comment by Kiarokh** [comment]
Interesting point @adrianschmidt . 
But then we already have a problems in our code, since we use icons for these purposes. 

For example, in `input-field.tsx` we have hard-coded icons that are from icons8. So consumers won't get them, right?

````tsx
	private getTrailingIcon() {
        if (this.isInvalid()) {
            return 'high_importance'; // 👈 This is the invalid icon that I'm embedding in the CSS in this PR
        }

        if (this.trailingIcon) {
            return this.trailingIcon;
        }

        if (this.showLink && this.type === 'email') {
            return 'filled_message';
        }

        if (this.showLink && this.type === 'tel') {
            return 'phone';
        }

        if (
            this.showLink &&
            (this.type === 'url' || this.type === 'urlAsText')
        ) {
            return 'external_link';
        }
    }
````

### Why embedded SVGs aren't good

Next problem is that the `currentColor` won't work in embedded SVGs. Because the embedded svg seems to become its own separate document. So it won't inherit the colors that we wanna apply with CSS. It means we have to hardcode an RGB value, and that will be on the way also when adding support to dark-mode. We can't use any of our own css variable colors neither.

## So, how to we go forward now?

For this specific case of visualizing invalid things, we don't need to use any SVG icons. We can simply add a pseudo element with `content: '!';` and some rounded corners and red color. But then I'll have to do this in all components that use the `high_importance` trailing icon or similar.

I don't know what other kinds of visualizations we have, which we use trailing icons for.

**Comment by adrianschmidt** [comment]
> Interesting point @adrianschmidt .
> But then we already have a problems in our code, since we use icons for these purposes.
>
> For example, in `input-field.tsx` we have hard-coded icons that are from icons8.
> 
> ```tsx
> 	private getTrailingIcon() {
>         if (this.isInvalid()) {
>             return 'high_importance'; // 👈 This is the invalid icon that I'm embedding in the CSS in this PR
>         }
> ```

Yeah, ideally we should decide on what path to take, and normalise our code so it works the same everywhere.

> So consumers won't get them, right?

Just to clarify: any add-ons in Lime CRM Web Client, or any other product where we supply Lime Elements and lime-icons8, _will_ get the icons from lime-icons8.

But anyone using Lime Elements in an environment where lime-icons8 is not installed, will have to supply some other icons. They can do that of course, and to get any "hardcoded" icons to show up, they just need to make sure they add some icon in a file using the correct file name. For example, @Befkadu1 mentioned possibly using Lime Elements for his own site, and @anderssonjohan uses Lime Elements for a private project too, and they will have to provide their own icons for any that aren't embedded. Embedding in some instances an not others seem like the worst of both worlds, as every client that isn't using icon8 will have different icons for the same thing in different components.

> ### Why embedded SVGs aren't good
> Next problem is that the `currentColor` won't work in embedded SVGs. Because the embedded svg seems to become its own separate document. So it won't inherit the colors that we wanna apply with CSS. It means we have to hardcode an RGB value, and that will be on the way also when adding support to dark-mode. We can't use any of our own css variable colors neither.

That's only a problem when embedding in css instead of in the html. In fact, limel-icon loads the svg data from the file and embeds it in the html, precisely because that's the only way we can change the colours through css when the svg data is embedded in the html, not when just linking it in an `img` tag.

**Comment by Kiarokh** [comment]
> They can do that of course, and to get any "hardcoded" icons to show up, they just need to make sure they add some icon in a file using the correct file name.

Sounds like we need to document which icons are hardcoded, and how they look, so they can do as you say.

So given the point discussed, it should be alright to add a conditional trailing icon, in the HTML. I'll do a fixup so we can see whether it's OK or not. ;)

**Comment by Kiarokh** [comment]
I made an issue here for the icons:
https://github.com/Lundalogik/lime-elements/issues/1272

Added icons in the HTML instead, and pushed a fixup.

**Comment by Kiarokh** [comment]
Not sure how we should go about this commit: 42547267dd0a126c4e526604e3c9646bf114f4d7

Where I just added a toggle to display invalid. Even though it's pedagogic, we don't have this toggle on other components. Should we add it there as well?

**Comment by adrianschmidt** [comment]
> Not sure how we should go about this commit: [4254726](https://github.com/Lundalogik/lime-elements/commit/42547267dd0a126c4e526604e3c9646bf114f4d7)
> 
> Where I just added a toggle to display invalid. Even though it's pedagogic, we don't have this toggle on other component examples. Should we add it there as well?

I think it's nice, but we don't need to add it to a bunch of other examples right now. I think we'll get options for `invalid` with #1248 anyway.

**Review by adrianschmidt — APPROVED** [review]

**Pull request merged**
