### PR TITLE
fix(date-picker): be able to change year with arrow buttons in month/quarter picker

### PR DESCRIPTION
**Pull request by maltja**
The problem was that handleOpen never was called which is where the event listeners are added. I guess this is because we only change the visibility of the portal which means that the picker never really opens and closes. However it closes if we select a date and therefore our custom event listeners are removed. 

Now we instead add the event listeners in init (called when the flatpicker is created) and remove them on destroy. 

fix Lundalogik/lime-elements#1247

## Review:
- [ ] Commits are [atomic](https://seesparkbox.com/foundry/atomic_commits_with_git)
- [ ] Commits have the correct *type* for the changes made
- [ ] Commits with *breaking changes* are marked as such

### Browsers tested:
(Check any that applies, it's ok to leave boxes unchecked if testing something didn't seem relevant.)

Windows:
- [ ] Chrome
- [ ] Edge
- [ ] Firefox

Linux:
- [ ] Chrome
- [ ] Firefox

macOS:
- [ ] Chrome
- [ ] Firefox
- [ ] Safari

Mobile:
- [ ] Chrome on Android
- [ ] iOS

### CODE REVIEW

**Review by hannahu — CHANGES_REQUESTED** [review]
If you've chosen a date, it's not possible to change the year anymore.

**Comment by maltja** [comment]
> If you've chosen a date, it's not possible to change the year anymore.

Nice catch! I copied those lines from the quarter picker where I thought the arrows worked. So we have the same bug for the quarter picker then. I will see if I can fix it for both the month and the quarter picker 🙂

**Comment by maltja** [comment]
> If you've chosen a date, it's not possible to change the year anymore.

fixed! 🙂

**Review by hannahu — APPROVED** [review]
Looks good! We still have some weird thing that a date gets some orange mark in the picker when changing year but that's another issue and not something critical :P

**Pull request merged**
