### PR TITLE
fix(select): don't render empty icons

### PR DESCRIPTION
**Pull request by LucyChyzhova**
fix: https://github.com/Lundalogik/lime-elements/issues/2618

## Review:
- [ ] Commits are [atomic](https://seesparkbox.com/foundry/atomic_commits_with_git)
- [ ] Commits have the correct *type* for the changes made
- [ ] Commits with *breaking changes* are marked as such

### Browsers tested:
(Check any that applies, it's ok to leave boxes unchecked if testing something didn't seem relevant.)

Windows:
- [ ] Chrome
- [ ] Edge
- [ ] Firefox

Linux:
- [ ] Chrome
- [ ] Firefox

macOS:
- [ ] Chrome
- [ ] Firefox
- [ ] Safari

Mobile:
- [ ] Chrome on Android
- [ ] iOS

### CODE REVIEW

**Review by jgroth — APPROVED** [review]

**Review by LawrenceBorst — COMMENTED** [review]
I see Johan already reviewed this. It looks good but I just wanted to point out we can expect similar problems elsewhere where `getIconName` is being used, like `chip-set.tsx`, `list-renderer`, `menu-list-renderer` etc. Not sure if this should be handled in one go from within the icon component using some dynamic CSS or if we should do it this way in other places

**Comment by Kiarokh** [comment]
🤔 maybe let's wait a little with merging this. 
When I added `getIconName` (when we deprecated `iconColor` `iconTitle` etc…) this problem didn't appear. I'm not sure why this has happened now. But if you see a potential that this happens in other places, maybe we should do a more global fix. Now I haven't really looked at why this is happening or what the fix is. Let's just do a visual inspection of other components and see if they also have any issues first.

**Comment by Kiarokh** [comment]
I didn't find this issue on other places. So I think it's better to merge this for now

**Pull request merged**
