### PR TITLE
fix(button-group): update value from outside

### LINKED ISSUE #2215: Button group: not possible to update the `selected` value from outside the component
## Current behavior

https://user-images.githubusercontent.com/35954987/230016496-411363a8-4402-4faf-963b-06d2626e0817.mov

## Expected behavior

It should be possible to change the selected value from outside, for example using a command or something.

## Environment

- **lime-elements** version: 
- Framework used: 
- Logs:

### PR DESCRIPTION
**Pull request by TommyLindh2**
Fixes #2215 

## Review:
- [ ] Commits are [atomic](https://seesparkbox.com/foundry/atomic_commits_with_git)
- [ ] Commits have the correct *type* for the changes made
- [ ] Commits with *breaking changes* are marked as such

### Browsers tested:
(Check any that applies, it's ok to leave boxes unchecked if testing something didn't seem relevant.)

Windows:
- [ ] Chrome
- [ ] Edge
- [ ] Firefox

Linux:
- [ ] Chrome
- [ ] Firefox

macOS:
- [ ] Chrome
- [ ] Firefox
- [ ] Safari

Mobile:
- [ ] Chrome on Android
- [ ] iOS

### CODE REVIEW

**Comment by TommyLindh2** [comment]
@Kiarokh can you relate this to the correct project and/or person? <3

**Review by LawrenceBorst — APPROVED** [review]
Code looks great, better than before :)
Tested the button-group value. Gets updated properly. Fixes the issue completely

**Pull request merged**
