### PR TITLE
fix(package): make all dependencies development dependencies only

### PR DESCRIPTION
**Pull request by adrianschmidt**
Since we use tree shaking during build, we already bundle all dependencies we need in our build output.

## Review:
- [ ] Commits are [atomic](https://seesparkbox.com/foundry/atomic_commits_with_git)
- [ ] Commits have the correct *type* for the changes made
- [ ] Commits with *breaking changes* are marked as such

### Browsers tested:
(Check any that applies, it's ok to leave boxes unchecked if testing something didn't seem relevant.)

Windows:
- [ ] Chrome
- [ ] Edge
- [ ] Firefox

Linux:
- [ ] Chrome
- [ ] Firefox

macOS:
- [ ] Chrome
- [ ] Firefox
- [ ] Safari

Mobile:
- [ ] Chrome on Android
- [ ] iOS

### CODE REVIEW

**Comment by adrianschmidt** [comment]
We agreed in the team that we should just merge this, and have it tested that way.

**Comment by anderssonjohan** [comment]
> We agreed in the team that we should just merge this, and have it tested that way.

@adrianschmidt @jgroth This change (once again) broke our packages which seems to need lime-element's dependencies to work. Was this intended?

This actually started for react, react-dom etc some weeks ago and we fixed it by installing the missing dependencies of lime-elements in our package.

Errors in the browser using this version after installing some of the missing packages:
Screen Shot 2021-05-14 at 17 33 38

If I install the package from the error message, that ones goes away and I get to the next error/missing package that is needed.

```
  "dependencies": {
    "@limetech/lime-elements": "^31.5.3",
    "@limetech/mdc-chips": "^4.0.1-p4.0.0.1",
    "@limetech/mdc-textfield": "^4.0.1-p4.0.0.1",
.....
```

When starting the stencil server in our package it's prints these warnings:

```
[ WARN  ]  Bundling Warning UNRESOLVED_IMPORT
           '@limetech/mdc-select/helper-text' is imported by
           ./node_modules/@limetech/lime-elements/dist/collection/components/select/select.js, but could not be
           resolved – treating it as an external dependency

[ WARN  ]  Bundling Warning UNRESOLVED_IMPORT
           '@rjsf/core' is imported by ./node_modules/@limetech/lime-elements/dist/collection/components/form/form.js,
           but could not be resolved – treating it as an external dependency

[ WARN  ]  Bundling Warning UNRESOLVED_IMPORT
           '@limetech/mdc-tab-bar/constants' is imported by
           ./node_modules/@limetech/lime-elements/dist/collection/components/tab-bar/tab-bar.js, but could not be
           resolved – treating it as an external dependency

[ WARN  ]  Bundling Warning UNRESOLVED_IMPORT
           '@limetech/mdc-list/constants' is imported by
           ./node_modules/@limetech/lime-elements/dist/collection/components/list/list.js, but could not be resolved –
           treating it as an external dependency

[ WARN  ]  Bundling Warning UNRESOLVED_IMPORT
           '@limetech/mdc-menu/constants' is imported by
           ./node_modules/@limetech/lime-elements/dist/collection/components/list/list.js, but could not be resolved –
           treating it as an external dependency

[ WARN  ]  Bundling Warning UNRESOLVED_IMPORT
           '@popperjs/core' is imported by
           ./node_modules/@limetech/lime-elements/dist/collection/components/portal/portal.js, but could not be
           resolved – treating it as an external dependency

[ WARN  ]  Bundling Warning UNRESOLVED_IMPORT
           'moment/locale/nb' is imported by
           ./node_modules/@limetech/lime-elements/dist/collection/components/date-picker/dateFormatter.js, but could
           not be resolved – treating it as an external dependency

[ WARN  ]  Bundling Warning UNRESOLVED_IMPORT
           'moment/locale/sv' is imported by
           ./node_modules/@limetech/lime-elements/dist/collection/components/date-picker/dateFormatter.js, but could
           not be resolved – treating it as an external dependency

[ WARN  ]  Bundling Warning UNRESOLVED_IMPORT
           'moment/moment' is imported by
           ./node_modules/@limetech/lime-elements/dist/collection/components/date-picker/dateFormatter.js, but could
           not be resolved – treating it as an external dependency

[ WARN  ]  Bundling Warning UNRESOLVED_IMPORT
           'moment/locale/nl' is imported by
           ./node_modules/@limetech/lime-elements/dist/collection/components/date-picker/dateFormatter.js, but could
           not be resolved – treating it as an external dependency

[ WARN  ]  Bundling Warning UNRESOLVED_IMPORT
           'moment/locale/fr' is imported by
           ./node_modules/@limetech/lime-elements/dist/collection/components/date-picker/dateFormatter.js, but could
           not be resolved – treating it as an external dependency

[ WARN  ]  Bundling Warning UNRESOLVED_IMPORT
           'moment/locale/fi' is imported by
           ./node_modules/@limetech/lime-elements/dist/collection/components/date-picker/dateFormatter.js, but could
           not be resolved – treating it as an external dependency

[ WARN  ]  Bundling Warning UNRESOLVED_IMPORT
           'moment/locale/da' is imported by
           ./node_modules/@limetech/lime-elements/dist/collection/components/date-picker/dateFormatter.js, but could
           not be resolved – treating it as an external dependency

[ WARN  ]  Bundling Warning UNRESOLVED_IMPORT
           '@rjsf/core/lib/components/fields/ArrayField' is imported by
           ./node_modules/@limetech/lime-elements/dist/collection/components/form/fields/array-field.js, but could not
           be resolved – treating it as an external dependency

[ WARN  ]  Bundling Warning UNRESOLVED_IMPORT
           '@rjsf/core/lib/components/fields/SchemaField' is imported by
           ./node_modules/@limetech/lime-elements/dist/collection/components/form/fields/schema-field.js, but could not
           be resolved – treating it as an external dependency

[ WARN  ]  Bundling Warning UNRESOLVED_IMPORT
           'moment/moment' is imported by
           ./node_modules/@limetech/lime-elements/dist/collection/components/date-picker/pickers/YearPicker.js, but
           could not be resolved – treating it as an external dependency

[ WARN  ]  Bundling Warning UNRESOLVED_IMPORT
           'moment/moment' is imported by
           ./node_modules/@limetech/lime-elements/dist/collection/components/date-picker/pickers/QuarterPicker.js, but
           could not be resolved – treating it as an external dependency

[ WARN  ]  Bundling Warning UNRESOLVED_IMPORT
           'flatpickr/dist/plugins/weekSelect/weekSelect' is imported by
           ./node_modules/@limetech/lime-elements/dist/collection/components/date-picker/pickers/WeekPicker.js, but
           could not be resolved – treating it as an external dependency

[ WARN  ]  Bundling Warning UNRESOLVED_IMPORT
           'moment/moment' is imported by
           ./node_modules/@limetech/lime-elements/dist/collection/components/date-picker/pickers/MonthPicker.js, but
           could not be resolved – treating it as an external dependency

[ WARN  ]  Bundling Warning UNRESOLVED_IMPORT
           'focus-trap' is imported by
           ./node_modules/@limetech/lime-elements/dist/collection/components/dialog/dialog.js, but could not be
           resolved – treating it as an external dependency

[ WARN  ]  Bundling Warning UNRESOLVED_IMPORT
           'awesome-debounce-promise' is imported by
           ./node_modules/@limetech/lime-elements/dist/collection/components/picker/picker.js, but could not be
           resolved – treating it as an external dependency

[ WARN  ]  Bundling Warning UNRESOLVED_IMPORT
           'react-shadow-dom-retarget-events' is imported by
           ./node_modules/@limetech/lime-elements/dist/collection/components/form/form.js, but could not be resolved –
           treating it as an external dependency

[ WARN  ]  Bundling Warning UNRESOLVED_IMPORT
           'tabulator-tables' is imported by
           ./node_modules/@limetech/lime-elements/dist/collection/components/table/table.js, but could not be resolved
           – treating it as an external dependency

[ WARN  ]  Bundling Warning UNRESOLVED_IMPORT
           '@rjsf/core/lib/utils' is imported by
           ./node_modules/@limetech/lime-elements/dist/collection/components/form/fields/field-helpers.js, but could
           not be resolved – treating it as an external dependency

[ WARN  ]  Bundling Warning UNRESOLVED_IMPORT
           'moment/locale/da' is imported by
           ./node_modules/@limetech/lime-elements/dist/collection/components/date-picker/pickers/Picker.js, but could
           not be resolved – treating it as an external dependency

```

So, warnings in the stencil server but errors in the browser console.

Here's an example project using lime-elements created after the above warnings started to show up for lodash-es, react and react-dom some weeks ago. 

https://github.com/sikorientering/sikresults/blob/06ddf7d6bd5f642cbea83a8ac6ee924c7aff8cc7/package.json#L40-L42

The fix back then was to install the dependencies of lime-elements in our package.

Could you give me advice on what's the correct way moving forward here? Installing all dependencies of lime-elements in my packages works, but it feels like I'm missing a piece of the puzzle here. 🙏

**Comment by jgroth** [comment]
My guess is that it breaks because Lime Elements is included in the build instead of just being consumed as is. It has already been built once so there should be no need to build it again from your end. If you do that then you are going to need all the dependencies as well I think.

I had a quick look at the repo and I think it might be this line that screws it up.
https://github.com/sikorientering/sikresults/blob/06ddf7d6bd5f642cbea83a8ac6ee924c7aff8cc7/src/components/app-root/app-root.tsx#L2

Instead of importing it like this, my suggestion is to include Lime Elements in `index.html` by using a `script` tag

**Comment by anderssonjohan** [comment]
> My guess is that it breaks because Lime Elements is included in the build instead of just being consumed as is. It has already been built once so there should be no need to build it again from your end. If you do that then you are going to need all the dependencies as well I think.
> 
> I had a quick look at the repo and I think it might be this line that screws it up.
> [sikorientering/sikresults@`06ddf7d`/src/components/app-root/app-root.tsx#L2](https://github.com/sikorientering/sikresults/blob/06ddf7d6bd5f642cbea83a8ac6ee924c7aff8cc7/src/components/app-root/app-root.tsx#L2)
> 
> Instead of importing it like this, my suggestion is to include Lime Elements in `index.html` by using a `script` tag

@jgroth Yes, I actually did that on purpose to avoid the need of a separate `script` tag so I guess that repo should fail like this, as long as I don't bring the libs needed to _build_ lime-elements. 
The error that forced us to include react/react-dom/lodash-es a couple of weeks ago was actually in a regular `lime-project` frontend, but I'll have to check it with the new version and see if it's the same thing or if this was just in my hobby project.

**Comment by anderssonjohan** [comment]
@adrianschmidt @jgroth @mjlime Our problem is now solved thanks to this PR! :pray: 😄 

I found this in our example code ([private repo commit](https://github.com/Lundalogik/limepkg-fullcalendar/commit/3143a30bd51b600473d1779e57ccb19eb88e7399)) which removed the need of the other dependencies.

This import typo of `Watch` was added with a sloppy "alt+enter" in VSCode, which picked the wrong one.

```
import { Languages, Option } from '@limetech/lime-elements';
import { Watch } from '@limetech/lime-elements/dist/types/stencil-public-runtime';
import { Component, h, State } from '@stencil/core';
```

Corrected code:
```
import { Languages, Option } from '@limetech/lime-elements';
import { Component, h, State, Watch } from '@stencil/core';
```

🤦

**Pull request merged**
