### PR TITLE
build(schema-form): migrate to rjsf v2

### PR DESCRIPTION
**Pull request by sampsonbryce**
## Review:
- [ ] Commits are [atomic](https://seesparkbox.com/foundry/atomic_commits_with_git)
- [ ] Commits have the correct *type* for the changes made
- [ ] Commits with *breaking changes* are marked as such

### Browsers tested:
(Check any that applies, it's ok to leave boxes unchecked if testing something didn't seem relevant.)

Windows:
- [ ] Chrome
- [ ] Edge
- [ ] Firefox

Linux:
- [ ] Chrome
- [ ] Firefox

macOS:
- [ ] Chrome
- [ ] Firefox
- [ ] Safari

Mobile:
- [ ] Chrome on Android
- [ ] iOS

### CODE REVIEW

**Comment by sampsonbryce** [comment]
This migration currently has issues. I am making this draft PR as documentation of the work to make the migration and the issues that arise. 

The main issue is, rjsf v2 changes how it bundles its dists. 

1. Rjsf uses a dynamic require (and always has) for some utility functions https://github.com/rjsf-team/react-jsonschema-form/blob/ff8b700aa8e06e66dc1c67921ea01496258fc375/packages/core/src/utils.js#L65
2. The dynamic requires are not resolved during the build of rjsf v2 es and cjs bundles. They were resolved in rjsf v1.
3. Rollup copies the contents of all the rjsf files verbatim to the final bundle files for lime-elements, at which point the directory structure of the rjsf es/cjs bundles not longer exists. So therefore the dynamic requires cannot resolve correctly. 

You can test the issue by installing this update into lime-admin and trying to compile. You should get an error along the lines of `Module not found: Error: Can't resolve './components/widgets' in '/path/to/lime-elements/dist/esm'`

Note: lime-elements compiles successfully. The issue only arises when importing lime-elements into another project.

**Comment by adrianschmidt** [comment]
FIY: I've rebased this on the latest master and resolved the conflicts, and will push momentarily.

**Comment by adrianschmidt** [comment]
We've got a PR open for updating to Stencil v2, and that updates Stencil's builder and, I think, also how it uses rollup. It might be worth checking if the problems with the dynamic requires might be solved by that? It's also probably worth making sure we have the currently latest version of rjsf v2, since things might possibly have changed there too since May…

PR for Stencil v2 is #977

**Comment by jgroth** [comment]
Seems like the dynamic require issues has been resolved now so we might be able to have another go at this 
https://github.com/rjsf-team/react-jsonschema-form/pull/2028

**Comment by jgroth** [comment]
I've updated to the latest version of the library now and made some changes that seemed to be required. It's hard to tell what breaking changes has been made since I've not found any changelogs. All tests pass and it seems to work fine in the documentation app as well as in Lime Admin 2. It would be great if you could test this with your addons @sampsonbryce since you have made some modifications to how the form behaves in some scenarios :slightly_smiling_face:

**Comment by hannahu** [comment]
It works good on the new object card as well. I'll assign you as a reviewer so you can test it out @sampsonbryce

**Comment by sampsonbryce** [comment]
@jgroth @hannahu this works great in the current version of limepkg-engage.

**Review by jgroth — APPROVED** [review]

**Pull request merged**
