### PR TITLE
fix(text-editor): ensure link popover opens in a decent location

### PR DESCRIPTION
**Pull request by Kiarokh**
fix https://github.com/Lundalogik/crm-feature/issues/4169

## Review:
- [ ] Commits are [atomic](https://seesparkbox.com/foundry/atomic_commits_with_git)
- [ ] Commits have the correct *type* for the changes made
- [ ] Commits with *breaking changes* are marked as such

### Browsers tested:
(Check any that applies, it's ok to leave boxes unchecked if testing something didn't seem relevant.)

Windows:
- [ ] Chrome
- [ ] Edge
- [ ] Firefox

Linux:
- [ ] Chrome
- [ ] Firefox

macOS:
- [ ] Chrome
- [ ] Firefox
- [ ] Safari

Mobile:
- [ ] Chrome on Android
- [ ] iOS

### CODE REVIEW

**Comment by john-traas** [comment]
This seems to introduce some strange behaviour to the editor-link-menu. 

https://github.com/Lundalogik/lime-elements/assets/122509723/2d23ba64-ac9d-4114-9fb9-63e86868b828

**Review by LucyChyzhova — APPROVED** [review]

**Comment by LucyChyzhova** [comment]
> This seems to introduce some strange behaviour to the editor-link-menu.
> 
>  Screen.Recording.2024-06-07.at.13.16.11.mov

yes, it what I noticed as well check the [comment](https://github.com/Lundalogik/crm-feature/issues/4169#issuecomment-2154587879), but actually that behaviour was not introduced here, this bug is a portal bug which we already had.

**Comment by Kiarokh** [comment]
> This seems to introduce some strange behaviour to the editor-link-menu.
> 
>  Screen.Recording.2024-06-07.at.13.16.11.mov

Yes. Gonna solve this separately. We have the same issue on main. Seems to be a `limel-portal` but https://github.com/Lundalogik/crm-feature/issues/4170

**Comment by Kiarokh** [comment]
additional not:

In the real app, this will "_almost_" never happen. This is because the text editor will never _(or should never)_ be as tall as the screen itself. However, we need to mitigate this issue from the component as well:

https://github.com/Lundalogik/crm-feature/issues/4171

**Comment by john-traas** [comment]
Emails in a chain of replies can get quite long. I think in the email story this could happen quite easily?

**Comment by LucyChyzhova** [comment]
yes, for sure. We are aware this case

**Pull request merged**
