### PR TITLE
fix(snackbar): make snackbar's label center alignment

### PR DESCRIPTION
**Pull request by LucyChyzhova**
When a `snakbar` has only a few words we have way too much empty space on the right side, I would suggest aligning a label to the center.

Before:
Screenshot 2023-03-28 at 13 30 17

Screenshot 2023-03-28 at 13 24 15

After:
Screenshot 2023-03-28 at 13 18 36

## Review:
- [x] Commits are [atomic](https://seesparkbox.com/foundry/atomic_commits_with_git)
- [x] Commits have the correct *type* for the changes made
- [x] Commits with *breaking changes* are marked as such

### Browsers tested:
(Check any that applies, it's ok to leave boxes unchecked if testing something didn't seem relevant.)

Windows:
- [ ] Chrome
- [ ] Edge
- [ ] Firefox

Linux:
- [ ] Chrome
- [ ] Firefox

macOS:
- [x] Chrome
- [ ] Firefox
- [ ] Safari

Mobile:
- [ ] Chrome on Android
- [ ] iOS

### CODE REVIEW

**Review by adrianschmidt — APPROVED** [review]
Nice and simple 👍

**Comment by Kiarokh** [comment]
Sorry I cam in too late before you approved this. 

This change looks nice in this example. But when the snackbar has buttons on the side, then this wouldn't look so nice anymore and alignments would be graphically off.

image

Instead of this approach, we can do one of the following

- make sure that the width of the snackbar is more dynamic based on the content. 
- or make sure that these styles are applied only if the text content is "small" and there are no buttons

**Comment by LucyChyzhova** [comment]
Good point! Thanks, Kia! Yes, you are right,  I will fix it and will make a new pr.

**Pull request merged**
