### PR TITLE
fix(table): don't scroll table to the left after each reload

### PR DESCRIPTION
**Pull request by jensgustafsson**
fix: Lundalogik/crm-feature#2027

## Review:
- [ ] Commits are [atomic](https://seesparkbox.com/foundry/atomic_commits_with_git)
- [ ] Commits have the correct *type* for the changes made
- [ ] Commits with *breaking changes* are marked as such

### Browsers tested:
(Check any that applies, it's ok to leave boxes unchecked if testing something didn't seem relevant.)

Windows:
- [ ] Chrome
- [ ] Edge
- [ ] Firefox

Linux:
- [ ] Chrome
- [ ] Firefox

macOS:
- [ ] Chrome
- [ ] Firefox
- [ ] Safari

Mobile:
- [ ] Chrome on Android
- [ ] iOS

### CODE REVIEW

**Comment by jgroth** [comment]
`setData` seems to be used here as well, should we replace it with `replaceData`?

https://github.com/Lundalogik/lime-elements/blob/5000fa40642bd8516aa6d04dd56fe510f92d7ba0/src/components/table/table.tsx#L354-L368

**Comment by hannahu** [comment]
> `setData` seems to be used here as well, should we replace it with `replaceData`?
> 
> https://github.com/Lundalogik/lime-elements/blob/5000fa40642bd8516aa6d04dd56fe510f92d7ba0/src/components/table/table.tsx#L354-L368

Saw it as well but thought we could keep it as it was but maybe we should use the same on both places.

**Comment by jensgustafsson** [comment]
> > `setData` seems to be used here as well, should we replace it with `replaceData`?
> > https://github.com/Lundalogik/lime-elements/blob/5000fa40642bd8516aa6d04dd56fe510f92d7ba0/src/components/table/table.tsx#L354-L368
> 
> Saw it as well but thought we could keep it as it was but maybe we should use the same on both places.


True. I thought it made sense to use `setData` here but I could look in to it once more and see if it makes sense to use it hear as well

**Comment by jensgustafsson** [comment]
> > > `setData` seems to be used here as well, should we replace it with `replaceData`?
> > > https://github.com/Lundalogik/lime-elements/blob/5000fa40642bd8516aa6d04dd56fe510f92d7ba0/src/components/table/table.tsx#L354-L368
> > 
> > 
> > Saw it as well but thought we could keep it as it was but maybe we should use the same on both places.
> 
> True. I thought it made sense to use `setData` here but I could look in to it once more and see if it makes sense to use it hear as well

`replaceData` seems to work equally well so I changed to that

**Review by hannahu — APPROVED** [review]

**Pull request merged**
