### PR TITLE
feat(help): add new component

### PR DESCRIPTION
**Pull request by Kiarokh**
Specially Intended to be used here: https://github.com/Lundalogik/lime-elements/pull/2622

## Review:
- [x] Commits are [atomic](https://seesparkbox.com/foundry/atomic_commits_with_git)
- [x] Commits have the correct *type* for the changes made
- [x] Commits with *breaking changes* are marked as such

### Browsers tested:
(Check any that applies, it's ok to leave boxes unchecked if testing something didn't seem relevant.)

Windows:
- [ ] Chrome
- [ ] Edge
- [ ] Firefox

Linux:
- [ ] Chrome
- [ ] Firefox

macOS:
- [x] Chrome
- [ ] Firefox
- [ ] Safari

Mobile:
- [ ] Chrome on Android
- [ ] iOS

### CODE REVIEW

**Comment by Kiarokh** [comment]
Specially Intended to be used here: https://github.com/Lundalogik/lime-elements/pull/2622
If you wanna see that, check it out

**Review by adrianschmidt — APPROVED** [review]
Looks good to me 👍

**Pull request merged**
