### PR TITLE
Transition helper line

### PR DESCRIPTION
**Pull request by Kiarokh**
fix https://github.com/Lundalogik/crm-feature/issues/3537
closes: https://github.com/Lundalogik/crm-feature/issues/3334

## Review:
- [ ] Commits are [atomic](https://seesparkbox.com/foundry/atomic_commits_with_git)
- [ ] Commits have the correct *type* for the changes made
- [ ] Commits with *breaking changes* are marked as such

### Browsers tested:
(Check any that applies, it's ok to leave boxes unchecked if testing something didn't seem relevant.)

Windows:
- [ ] Chrome
- [ ] Edge
- [ ] Firefox

Linux:
- [ ] Chrome
- [ ] Firefox

macOS:
- [ ] Chrome
- [ ] Firefox
- [ ] Safari

Mobile:
- [ ] Chrome on Android
- [ ] iOS

### CODE REVIEW

**Comment by Kiarokh** [comment]
There will be a **know** issue in **Input Field > Auto complete** and in **Select**. The issue is that _when there are auto completion suggestions_ or _the select dropdown menu_ (basically, when the portal is open), the helper line is not displayed directly. 

But I consider it as "very unimportant", and we can ignore it.

The issue is that when there is a helperText && there are suggestions, the portal (with the list of suggestions for example) is rendered before the helper text animation is run. This means the height of the component is not yet "finalized" and the portal doesn't know it yet. The portal doesn't know that it should wait for the helperText to get rendered and get done with increasing the accumulated height of the component. Therefore, the portal opens right below the input-field, and covers the helper-line.

However, this is not a serious problem, because:

- **For the auto completions:** as soon as the user types something (or if they scroll), the portal recalculates its location and aligns itself correctly. So the users will see the helper text immediately after that.

https://github.com/Lundalogik/lime-elements/assets/35954987/935dbeab-9496-4ec9-9179-9e5d4f9e5feb

- **For the Select:** when you have selected an option, the dropdown closes and you see the helper text anyways.
- 
Therefore I believe that we should not try to fix this issue by setting a timeout or similar, and just move on.

**Review by LucyChyzhova — APPROVED** [review]
Looks really good! 💫

**Pull request merged**
