### PR TITLE
fix(button-group): fix visual defects on Firefox cause by user agent …

### PR DESCRIPTION
**Pull request by Kiarokh**
…stylesheets
fix: https://github.com/Lundalogik/crm-feature/issues/1353
fix: https://github.com/Lundalogik/lime-elements/issues/942

## Review:
- [ ] Commits are [atomic](https://seesparkbox.com/foundry/atomic_commits_with_git)
- [ ] Commits have the correct *type* for the changes made
- [ ] Commits with *breaking changes* are marked as such

### Browsers tested:
(Check any that applies, it's ok to leave boxes unchecked if testing something didn't seem relevant.)

Windows:
- [ ] Chrome
- [ ] Edge
- [ ] Firefox

Linux:
- [ ] Chrome
- [ ] Firefox

macOS:
- [x] Chrome
- [x] Firefox
- [x] Safari

Mobile:
- [ ] Chrome on Android
- [ ] iOS

### CODE REVIEW

**Comment by adrianschmidt** [comment]
This probably fixes #943 too, since it seems to be the same issue.

**Comment by Kiarokh** [comment]
> This probably fixes #943 too, since it seems to be the same issue.

Did you link to wrong issue? #943 is this very PR :P

**Comment by adrianschmidt** [comment]
> > This probably fixes #943 too, since it seems to be the same issue.
> 
> Did you link to wrong issue? #943 is this very PR :P

Indeed I did 😆

#942 was what I meant to link!

**Comment by Kiarokh** [comment]
> #942 was what I meant to link!

Oh Lord! His Firefox is more disgusting than mine. Yes, this will fix that too. I'll update and link to it.
I had tried earlier to fix [a similar issue for iOS](https://github.com/Lundalogik/crm-feature/issues/1320), but this PR should even fix that as well.

**Review by maltja — APPROVED** [review]
I have tested it but could not replicate the error.

**Pull request merged**
